"""
Pine Script v5 generator.
Converts strategy configs into valid TradingView Pine Script v5 code.
"""

import datetime
from typing import Dict, Any, List
from pathlib import Path


PINESCRIPT_DIR = Path("trading/workspace/pinescript")


def generate_pine_script(strategy: Dict[str, Any]) -> str:
    """Generate a complete Pine Script v5 strategy from a strategy config."""
    name = strategy.get("name", "Generated_Strategy")
    timeframe = strategy.get("timeframe", "4h")
    indicators = strategy.get("indicators", [])
    rules = strategy.get("rules", {})
    entry_rules = rules.get("entry", [])
    exit_rules = rules.get("exit", [])
    direction = strategy.get("direction", "long")

    lines = []
    lines.append(f'// Generated by TradingClaw — {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}')
    lines.append(f'// Strategy: {name}')
    lines.append(f'//@version=5')
    lines.append(f'strategy("{name}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_value=0.1)')
    lines.append("")

    # Generate indicator declarations
    indicator_vars = {}
    for ind in indicators:
        ind_lines, ind_vars = _generate_indicator(ind)
        lines.extend(ind_lines)
        indicator_vars.update(ind_vars)
        lines.append("")

    # Generate entry conditions
    lines.append("// Entry conditions")
    entry_conditions = []
    for rule in entry_rules:
        cond = _generate_condition(rule, indicator_vars)
        if cond:
            entry_conditions.append(cond)

    if entry_conditions:
        entry_combined = " and ".join(entry_conditions)
        lines.append(f"longCondition = {entry_combined}")
    else:
        lines.append("longCondition = false")

    lines.append("")

    # Generate exit conditions
    lines.append("// Exit conditions")
    exit_conditions = []
    for rule in exit_rules:
        cond = _generate_condition(rule, indicator_vars)
        if cond:
            exit_conditions.append(cond)

    if exit_conditions:
        exit_combined = " or ".join(exit_conditions)
        lines.append(f"exitCondition = {exit_combined}")
    else:
        lines.append("exitCondition = false")

    lines.append("")

    # Generate strategy entries/exits
    lines.append("// Strategy execution")
    if direction in ("long", "both"):
        lines.append('if longCondition')
        lines.append('    strategy.entry("Long", strategy.long)')
        lines.append('if exitCondition')
        lines.append('    strategy.close("Long")')

    if direction in ("short", "both"):
        lines.append("")
        lines.append("// Short entries (invert conditions)")
        lines.append('shortCondition = exitCondition')
        lines.append('shortExit = longCondition')
        lines.append('if shortCondition')
        lines.append('    strategy.entry("Short", strategy.short)')
        lines.append('if shortExit')
        lines.append('    strategy.close("Short")')

    lines.append("")

    # Plot indicators
    lines.append("// Plots")
    for ind in indicators:
        plot_lines = _generate_plots(ind, indicator_vars)
        lines.extend(plot_lines)

    # Plot signals
    lines.append("")
    lines.append("// Signal markers")
    lines.append('plotshape(longCondition, title="Long", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)')
    lines.append('plotshape(exitCondition, title="Exit", location=location.abovebar, color=color.red, style=shape.triangledown, size=size.small)')

    return "\n".join(lines)


def _generate_indicator(ind: Dict) -> tuple:
    """Generate Pine Script indicator declaration. Returns (lines, var_map)."""
    name = ind["name"].upper()
    params = ind.get("params", {})
    lines = []
    var_map = {}

    if name == "RSI":
        length = params.get("length", 14)
        var_name = f"rsi_{length}"
        lines.append(f"// RSI({length})")
        lines.append(f"{var_name} = ta.rsi(close, {length})")
        var_map[var_name] = var_name

    elif name == "EMA":
        length = params.get("length", 20)
        var_name = f"ema_{length}"
        lines.append(f"// EMA({length})")
        lines.append(f"{var_name} = ta.ema(close, {length})")
        var_map[var_name] = var_name

    elif name == "SMA":
        length = params.get("length", 20)
        var_name = f"sma_{length}"
        lines.append(f"// SMA({length})")
        lines.append(f"{var_name} = ta.sma(close, {length})")
        var_map[var_name] = var_name

    elif name == "MACD":
        fast = params.get("fast", 12)
        slow = params.get("slow", 26)
        signal = params.get("signal", 9)
        lines.append(f"// MACD({fast}, {slow}, {signal})")
        lines.append(f"[macdLine, signalLine, macdHist] = ta.macd(close, {fast}, {slow}, {signal})")
        var_map[f"MACDh_{fast}_{slow}_{signal}"] = "macdHist"
        var_map[f"MACD_{fast}_{slow}_{signal}"] = "macdLine"
        var_map[f"MACDs_{fast}_{slow}_{signal}"] = "signalLine"

    elif name == "BBANDS":
        length = params.get("length", 20)
        std = params.get("std", 2.0)
        lines.append(f"// Bollinger Bands({length}, {std})")
        lines.append(f"[bbUpper, bbBasis, bbLower] = ta.bb(close, {length}, {std})")
        var_map[f"BBU_{length}_{std}"] = "bbUpper"
        var_map[f"BBM_{length}_{std}"] = "bbBasis"
        var_map[f"BBL_{length}_{std}"] = "bbLower"

    elif name == "ATR":
        length = params.get("length", 14)
        var_name = f"atr_{length}"
        lines.append(f"// ATR({length})")
        lines.append(f"{var_name} = ta.atr({length})")
        var_map[var_name] = var_name

    elif name == "STOCH":
        k = params.get("k", 14)
        d = params.get("d", 3)
        smooth_k = params.get("smooth_k", 3)
        lines.append(f"// Stochastic({k}, {d}, {smooth_k})")
        lines.append(f"stochK = ta.stoch(close, high, low, {k})")
        lines.append(f"stochD = ta.sma(stochK, {d})")
        var_map[f"STOCHk_{k}_{d}_{smooth_k}"] = "stochK"
        var_map[f"STOCHd_{k}_{d}_{smooth_k}"] = "stochD"

    elif name == "ADX":
        length = params.get("length", 14)
        lines.append(f"// ADX({length})")
        lines.append(f"[diPlus, diMinus, adxValue] = ta.dmi({length}, {length})")
        var_map[f"ADX_{length}"] = "adxValue"

    elif name == "SUPERTREND":
        length = params.get("length", 7)
        multiplier = params.get("multiplier", 3.0)
        lines.append(f"// Supertrend({length}, {multiplier})")
        lines.append(f"[supertrend, direction] = ta.supertrend({multiplier}, {length})")
        var_map[f"SUPERT_{length}_{multiplier}"] = "supertrend"
        var_map[f"SUPERTd_{length}_{multiplier}"] = "direction"

    return lines, var_map


def _generate_condition(rule: Dict, var_map: Dict) -> str:
    """Generate a Pine Script condition from a rule dict."""
    op = rule.get("operator", "crosses_above")
    left = _resolve_pine_operand(rule.get("left"), var_map)
    right = _resolve_pine_operand(rule.get("right"), var_map)

    if not left or not right:
        return ""

    if op == "crosses_above":
        return f"ta.crossover({left}, {right})"
    elif op == "crosses_below":
        return f"ta.crossunder({left}, {right})"
    elif op == "greater_than":
        return f"{left} > {right}"
    elif op == "less_than":
        return f"{left} < {right}"
    elif op == "equals":
        return f"{left} == {right}"
    return ""


def _resolve_pine_operand(operand, var_map: Dict) -> str:
    """Resolve an operand to Pine Script variable name."""
    if operand is None:
        return ""
    if isinstance(operand, (int, float)):
        return str(operand)
    if isinstance(operand, str):
        # Check var_map first
        if operand in var_map:
            return var_map[operand]
        # Common price fields
        if operand in ("close", "open", "high", "low", "volume"):
            return operand
        # Try as number
        try:
            float(operand)
            return operand
        except ValueError:
            pass
        # Return as-is (might be a variable defined elsewhere)
        return operand
    return ""


def _generate_plots(ind: Dict, var_map: Dict) -> List[str]:
    """Generate plot statements for an indicator."""
    name = ind["name"].upper()
    params = ind.get("params", {})
    lines = []

    if name == "EMA":
        length = params.get("length", 20)
        var = var_map.get(f"ema_{length}", f"ema_{length}")
        lines.append(f'plot({var}, title="EMA {length}", color=color.blue, linewidth=1)')

    elif name == "SMA":
        length = params.get("length", 20)
        var = var_map.get(f"sma_{length}", f"sma_{length}")
        lines.append(f'plot({var}, title="SMA {length}", color=color.orange, linewidth=1)')

    elif name == "BBANDS":
        length = params.get("length", 20)
        std = params.get("std", 2.0)
        lines.append(f'plot(bbUpper, title="BB Upper", color=color.gray)')
        lines.append(f'plot(bbBasis, title="BB Basis", color=color.yellow)')
        lines.append(f'plot(bbLower, title="BB Lower", color=color.gray)')

    elif name == "SUPERTREND":
        lines.append(f'plot(supertrend, title="Supertrend", color=direction < 0 ? color.green : color.red, linewidth=2)')

    return lines


def save_pine_script(strategy: Dict[str, Any], output_dir: str = None) -> str:
    """Generate and save Pine Script to file."""
    script = generate_pine_script(strategy)
    save_dir = Path(output_dir) if output_dir else PINESCRIPT_DIR
    save_dir.mkdir(parents=True, exist_ok=True)

    name = strategy.get("name", "strategy")
    filepath = save_dir / f"{name}.pine"
    with open(filepath, "w") as f:
        f.write(script)
    return str(filepath)
